import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Echo5 Digital",
  description: "Generated by AI Studio",
};

// Sitewide JSON-LD (Organization/LocalBusiness + WebSite). Injected as a literal
// object by project-writer.ts from verified facts only — never from AI output —
// so this can never contain a fabricated address, phone, or credential.
const SITEWIDE_SCHEMA = [{"@context":"https://schema.org","@type":"LocalBusiness","name":"Echo5 Digital","url":"https://example.com","address":{"@type":"PostalAddress","streetAddress":"Houston / Sugar Land, Texas"},"telephone":"713-489-7004","email":"hello@echo5digital.com","areaServed":"Houston, Sugar Land, Texas (primary); National U.S. (secondary); Operations Support: Kochi, Kerala, India"},{"@context":"https://schema.org","@type":"WebSite","name":"Echo5 Digital","url":"https://example.com"}];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-900 antialiased">
        {SITEWIDE_SCHEMA.map((schema: Record<string, unknown>, i: number) => (
          <script
            key={i}
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
          />
        ))}
        {children}
      </body>
    </html>
  );
}
